/*
 * This file is generated by jOOQ.
 */
package org.jooq.dsl.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.dsl.tables.Group;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class GroupRecord extends UpdatableRecordImpl<GroupRecord> implements Record8<Integer, String, String, String, JSONB, JSONB, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1346051602;

    /**
     * Setter for <code>mvp.group.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mvp.group.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mvp.group.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mvp.group.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mvp.group.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mvp.group.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mvp.group.desc</code>.
     */
    public void setDesc(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mvp.group.desc</code>.
     */
    public String getDesc() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mvp.group.custom_schema</code>.
     */
    public void setCustomSchema(JSONB value) {
        set(4, value);
    }

    /**
     * Getter for <code>mvp.group.custom_schema</code>.
     */
    public JSONB getCustomSchema() {
        return (JSONB) get(4);
    }

    /**
     * Setter for <code>mvp.group.custom_forms</code>.
     */
    public void setCustomForms(JSONB value) {
        set(5, value);
    }

    /**
     * Getter for <code>mvp.group.custom_forms</code>.
     */
    public JSONB getCustomForms() {
        return (JSONB) get(5);
    }

    /**
     * Setter for <code>mvp.group.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>mvp.group.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>mvp.group.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>mvp.group.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, String, JSONB, JSONB, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, String, String, JSONB, JSONB, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Group.GROUP.ID;
    }

    @Override
    public Field<String> field2() {
        return Group.GROUP.CODE;
    }

    @Override
    public Field<String> field3() {
        return Group.GROUP.NAME;
    }

    @Override
    public Field<String> field4() {
        return Group.GROUP.DESC;
    }

    @Override
    public Field<JSONB> field5() {
        return Group.GROUP.CUSTOM_SCHEMA;
    }

    @Override
    public Field<JSONB> field6() {
        return Group.GROUP.CUSTOM_FORMS;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Group.GROUP.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Group.GROUP.UPDATED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDesc();
    }

    @Override
    public JSONB component5() {
        return getCustomSchema();
    }

    @Override
    public JSONB component6() {
        return getCustomForms();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component8() {
        return getUpdatedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDesc();
    }

    @Override
    public JSONB value5() {
        return getCustomSchema();
    }

    @Override
    public JSONB value6() {
        return getCustomForms();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value8() {
        return getUpdatedAt();
    }

    @Override
    public GroupRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GroupRecord value2(String value) {
        setCode(value);
        return this;
    }

    @Override
    public GroupRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public GroupRecord value4(String value) {
        setDesc(value);
        return this;
    }

    @Override
    public GroupRecord value5(JSONB value) {
        setCustomSchema(value);
        return this;
    }

    @Override
    public GroupRecord value6(JSONB value) {
        setCustomForms(value);
        return this;
    }

    @Override
    public GroupRecord value7(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public GroupRecord value8(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public GroupRecord values(Integer value1, String value2, String value3, String value4, JSONB value5, JSONB value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GroupRecord
     */
    public GroupRecord() {
        super(Group.GROUP);
    }

    /**
     * Create a detached, initialised GroupRecord
     */
    public GroupRecord(Integer id, String code, String name, String desc, JSONB customSchema, JSONB customForms, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Group.GROUP);

        set(0, id);
        set(1, code);
        set(2, name);
        set(3, desc);
        set(4, customSchema);
        set(5, customForms);
        set(6, createdAt);
        set(7, updatedAt);
    }
}
