/*
 * This file is generated by jOOQ.
 */
package org.jooq.dsl.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.dsl.tables.Translation;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TranslationRecord extends UpdatableRecordImpl<TranslationRecord> implements Record6<Integer, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -1280410887;

    /**
     * Setter for <code>mvp.translation.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mvp.translation.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mvp.translation.key</code>.
     */
    public void setKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mvp.translation.key</code>.
     */
    public String getKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mvp.translation.locale</code>.
     */
    public void setLocale(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mvp.translation.locale</code>.
     */
    public String getLocale() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mvp.translation.value</code>.
     */
    public void setValue(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mvp.translation.value</code>.
     */
    public String getValue() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mvp.translation.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>mvp.translation.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>mvp.translation.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>mvp.translation.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Translation.TRANSLATION.ID;
    }

    @Override
    public Field<String> field2() {
        return Translation.TRANSLATION.KEY;
    }

    @Override
    public Field<String> field3() {
        return Translation.TRANSLATION.LOCALE;
    }

    @Override
    public Field<String> field4() {
        return Translation.TRANSLATION.VALUE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Translation.TRANSLATION.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Translation.TRANSLATION.UPDATED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getKey();
    }

    @Override
    public String component3() {
        return getLocale();
    }

    @Override
    public String component4() {
        return getValue();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdatedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getKey();
    }

    @Override
    public String value3() {
        return getLocale();
    }

    @Override
    public String value4() {
        return getValue();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdatedAt();
    }

    @Override
    public TranslationRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TranslationRecord value2(String value) {
        setKey(value);
        return this;
    }

    @Override
    public TranslationRecord value3(String value) {
        setLocale(value);
        return this;
    }

    @Override
    public TranslationRecord value4(String value) {
        setValue(value);
        return this;
    }

    @Override
    public TranslationRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public TranslationRecord value6(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public TranslationRecord values(Integer value1, String value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TranslationRecord
     */
    public TranslationRecord() {
        super(Translation.TRANSLATION);
    }

    /**
     * Create a detached, initialised TranslationRecord
     */
    public TranslationRecord(Integer id, String key, String locale, String value, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Translation.TRANSLATION);

        set(0, id);
        set(1, key);
        set(2, locale);
        set(3, value);
        set(4, createdAt);
        set(5, updatedAt);
    }
}
