/*
 * This file is generated by jOOQ.
 */
package org.jooq.dsl;


import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.dsl.tables.Entry;
import org.jooq.dsl.tables.FlywaySchemaHistory;
import org.jooq.dsl.tables.Group;
import org.jooq.dsl.tables.Translation;
import org.jooq.dsl.tables.records.EntryRecord;
import org.jooq.dsl.tables.records.FlywaySchemaHistoryRecord;
import org.jooq.dsl.tables.records.GroupRecord;
import org.jooq.dsl.tables.records.TranslationRecord;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of
 * the <code>mvp</code> schema.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<EntryRecord, Integer> IDENTITY_ENTRY = Identities0.IDENTITY_ENTRY;
    public static final Identity<GroupRecord, Integer> IDENTITY_GROUP = Identities0.IDENTITY_GROUP;
    public static final Identity<TranslationRecord, Integer> IDENTITY_TRANSLATION = Identities0.IDENTITY_TRANSLATION;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EntryRecord> ENTRY_PKEY = UniqueKeys0.ENTRY_PKEY;
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = UniqueKeys0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final UniqueKey<GroupRecord> GROUP_PKEY = UniqueKeys0.GROUP_PKEY;
    public static final UniqueKey<TranslationRecord> TRANSLATION_PKEY = UniqueKeys0.TRANSLATION_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<EntryRecord, Integer> IDENTITY_ENTRY = Internal.createIdentity(Entry.ENTRY, Entry.ENTRY.ID);
        public static Identity<GroupRecord, Integer> IDENTITY_GROUP = Internal.createIdentity(Group.GROUP, Group.GROUP.ID);
        public static Identity<TranslationRecord, Integer> IDENTITY_TRANSLATION = Internal.createIdentity(Translation.TRANSLATION, Translation.TRANSLATION.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<EntryRecord> ENTRY_PKEY = Internal.createUniqueKey(Entry.ENTRY, "entry_pkey", new TableField[]{Entry.ENTRY.ID}, true);
        public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, "flyway_schema_history_pk", new TableField[]{FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK}, true);
        public static final UniqueKey<GroupRecord> GROUP_PKEY = Internal.createUniqueKey(Group.GROUP, "group_pkey", new TableField[]{Group.GROUP.ID}, true);
        public static final UniqueKey<TranslationRecord> TRANSLATION_PKEY = Internal.createUniqueKey(Translation.TRANSLATION, "translation_pkey", new TableField[]{Translation.TRANSLATION.ID}, true);
    }
}
