/*
 * This file is generated by jOOQ.
 */
package org.jooq.dsl;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.dsl.tables.Entry;
import org.jooq.dsl.tables.FlywaySchemaHistory;
import org.jooq.dsl.tables.Group;
import org.jooq.dsl.tables.Translation;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Mvp extends SchemaImpl {

    private static final long serialVersionUID = -1854222697;

    /**
     * The reference instance of <code>mvp</code>
     */
    public static final Mvp MVP = new Mvp();

    /**
     * The table <code>mvp.entry</code>.
     */
    public final Entry ENTRY = Entry.ENTRY;

    /**
     * The table <code>mvp.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>mvp.group</code>.
     */
    public final Group GROUP = Group.GROUP;

    /**
     * The table <code>mvp.translation</code>.
     */
    public final Translation TRANSLATION = Translation.TRANSLATION;

    /**
     * No further instances allowed
     */
    private Mvp() {
        super("mvp", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
                Sequences.ENTRY_ID_SEQ,
                Sequences.GROUP_ID_SEQ,
                Sequences.TRANSLATION_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
                Entry.ENTRY,
                FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
                Group.GROUP,
                Translation.TRANSLATION);
    }
}
