/*
 * This file is generated by jOOQ.
 */
package org.jooq.dsl;


import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in mvp
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Sequences {

    /**
     * The sequence <code>mvp.entry_id_seq</code>
     */
    public static final Sequence<Integer> ENTRY_ID_SEQ = Internal.createSequence("entry_id_seq", Mvp.MVP, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>mvp.group_id_seq</code>
     */
    public static final Sequence<Integer> GROUP_ID_SEQ = Internal.createSequence("group_id_seq", Mvp.MVP, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>mvp.translation_id_seq</code>
     */
    public static final Sequence<Integer> TRANSLATION_ID_SEQ = Internal.createSequence("translation_id_seq", Mvp.MVP, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
