/*
 * This file is generated by jOOQ.
 */
package org.jooq.dsl;


import org.jooq.dsl.tables.Entry;
import org.jooq.dsl.tables.FlywaySchemaHistory;
import org.jooq.dsl.tables.Group;
import org.jooq.dsl.tables.Translation;


/**
 * Convenience access to all tables in mvp
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>mvp.entry</code>.
     */
    public static final Entry ENTRY = Entry.ENTRY;

    /**
     * The table <code>mvp.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>mvp.group</code>.
     */
    public static final Group GROUP = Group.GROUP;

    /**
     * The table <code>mvp.translation</code>.
     */
    public static final Translation TRANSLATION = Translation.TRANSLATION;
}
