/*
 * Reference Data MS
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.4.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * CustomFieldsFast
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-23T05:24:28.400+08:00[Asia/Singapore]")
public class CustomFieldsFast {
  @SerializedName("bank_name")
  private String bankName = null;

  @SerializedName("bic_code")
  private String bicCode = null;

  @SerializedName("extra_payer_account_types")
  private List<String> extraPayerAccountTypes = null;

  @SerializedName("extra_recipient_account_types")
  private List<String> extraRecipientAccountTypes = null;

  public CustomFieldsFast bankName(String bankName) {
    this.bankName = bankName;
    return this;
  }

   /**
   * Get bankName
   * @return bankName
  **/
  @Schema(description = "")
  public String getBankName() {
    return bankName;
  }

  public void setBankName(String bankName) {
    this.bankName = bankName;
  }

  public CustomFieldsFast bicCode(String bicCode) {
    this.bicCode = bicCode;
    return this;
  }

   /**
   * Get bicCode
   * @return bicCode
  **/
  @Schema(description = "")
  public String getBicCode() {
    return bicCode;
  }

  public void setBicCode(String bicCode) {
    this.bicCode = bicCode;
  }

  public CustomFieldsFast extraPayerAccountTypes(List<String> extraPayerAccountTypes) {
    this.extraPayerAccountTypes = extraPayerAccountTypes;
    return this;
  }

  public CustomFieldsFast addExtraPayerAccountTypesItem(String extraPayerAccountTypesItem) {
    if (this.extraPayerAccountTypes == null) {
      this.extraPayerAccountTypes = new ArrayList<String>();
    }
    this.extraPayerAccountTypes.add(extraPayerAccountTypesItem);
    return this;
  }

   /**
   * Get extraPayerAccountTypes
   * @return extraPayerAccountTypes
  **/
  @Schema(description = "")
  public List<String> getExtraPayerAccountTypes() {
    return extraPayerAccountTypes;
  }

  public void setExtraPayerAccountTypes(List<String> extraPayerAccountTypes) {
    this.extraPayerAccountTypes = extraPayerAccountTypes;
  }

  public CustomFieldsFast extraRecipientAccountTypes(List<String> extraRecipientAccountTypes) {
    this.extraRecipientAccountTypes = extraRecipientAccountTypes;
    return this;
  }

  public CustomFieldsFast addExtraRecipientAccountTypesItem(String extraRecipientAccountTypesItem) {
    if (this.extraRecipientAccountTypes == null) {
      this.extraRecipientAccountTypes = new ArrayList<String>();
    }
    this.extraRecipientAccountTypes.add(extraRecipientAccountTypesItem);
    return this;
  }

   /**
   * Get extraRecipientAccountTypes
   * @return extraRecipientAccountTypes
  **/
  @Schema(description = "")
  public List<String> getExtraRecipientAccountTypes() {
    return extraRecipientAccountTypes;
  }

  public void setExtraRecipientAccountTypes(List<String> extraRecipientAccountTypes) {
    this.extraRecipientAccountTypes = extraRecipientAccountTypes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomFieldsFast customFieldsFast = (CustomFieldsFast) o;
    return Objects.equals(this.bankName, customFieldsFast.bankName) &&
        Objects.equals(this.bicCode, customFieldsFast.bicCode) &&
        Objects.equals(this.extraPayerAccountTypes, customFieldsFast.extraPayerAccountTypes) &&
        Objects.equals(this.extraRecipientAccountTypes, customFieldsFast.extraRecipientAccountTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bankName, bicCode, extraPayerAccountTypes, extraRecipientAccountTypes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomFieldsFast {\n");
    
    sb.append("    bankName: ").append(toIndentedString(bankName)).append("\n");
    sb.append("    bicCode: ").append(toIndentedString(bicCode)).append("\n");
    sb.append("    extraPayerAccountTypes: ").append(toIndentedString(extraPayerAccountTypes)).append("\n");
    sb.append("    extraRecipientAccountTypes: ").append(toIndentedString(extraRecipientAccountTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
