/*
 * Reference Data MS
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.4.6
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.JSONForms;
import io.swagger.client.model.JSONScheme;
import io.swagger.client.model.Permissions;
import io.swagger.v3.oas.annotations.media.Schema;

import java.io.IOException;

/**
 * RefGroup
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-16T20:17:39.272+08:00[Asia/Singapore]")
public class RefGroup {
    @SerializedName("code")
    private String code = null;

    @SerializedName("name")
    private String name = null;

    @SerializedName("desc")
    private String desc = null;

    @SerializedName("custom_schema")
    private JSONScheme customSchema = null;

    @SerializedName("custom_forms")
    private JSONForms customForms = null;

    @SerializedName("allow")
    private Permissions allow = null;

    public RefGroup code(String code) {
        this.code = code;
        return this;
    }

    /**
     * Get code
     *
     * @return code
     **/
    @Schema(description = "")
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public RefGroup name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @Schema(required = true, description = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public RefGroup desc(String desc) {
        this.desc = desc;
        return this;
    }

    /**
     * Get desc
     *
     * @return desc
     **/
    @Schema(required = true, description = "")
    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public RefGroup customSchema(JSONScheme customSchema) {
        this.customSchema = customSchema;
        return this;
    }

    /**
     * Get customSchema
     *
     * @return customSchema
     **/
    @Schema(required = true, description = "")
    public JSONScheme getCustomSchema() {
        return customSchema;
    }

    public void setCustomSchema(JSONScheme customSchema) {
        this.customSchema = customSchema;
    }

    public RefGroup customForms(JSONForms customForms) {
        this.customForms = customForms;
        return this;
    }

    /**
     * Get customForms
     *
     * @return customForms
     **/
    @Schema(required = true, description = "")
    public JSONForms getCustomForms() {
        return customForms;
    }

    public void setCustomForms(JSONForms customForms) {
        this.customForms = customForms;
    }

    public RefGroup allow(Permissions allow) {
        this.allow = allow;
        return this;
    }

    /**
     * Get allow
     *
     * @return allow
     **/
    @Schema(description = "")
    public Permissions getAllow() {
        return allow;
    }

    public void setAllow(Permissions allow) {
        this.allow = allow;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RefGroup refGroup = (RefGroup) o;
        return Objects.equals(this.code, refGroup.code) &&
                Objects.equals(this.name, refGroup.name) &&
                Objects.equals(this.desc, refGroup.desc) &&
                Objects.equals(this.customSchema, refGroup.customSchema) &&
                Objects.equals(this.customForms, refGroup.customForms) &&
                Objects.equals(this.allow, refGroup.allow);
    }

    @Override
    public int hashCode() {
        return Objects.hash(code, name, desc, customSchema, customForms, allow);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RefGroup {\n");

        sb.append("    code: ").append(toIndentedString(code)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    desc: ").append(toIndentedString(desc)).append("\n");
        sb.append("    customSchema: ").append(toIndentedString(customSchema)).append("\n");
        sb.append("    customForms: ").append(toIndentedString(customForms)).append("\n");
        sb.append("    allow: ").append(toIndentedString(allow)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
