/*
 * Reference Data MS
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.4.6
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ExtraInfo;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InfraApi
 */
@Ignore
public class InfraApiTest {

    private final InfraApi api = new InfraApi();

    /**
     * Server heartbeats
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void healthGetTest() throws ApiException {
        ExtraInfo response = api.healthGet();

        // TODO: test validations
    }
}
